---
  .travis.yml:
    hc_secure: "itAZyVjEnBMYN93unTTPsgwx0VJRuMV/lZAIzbTSI60W8scJ/tu1rg+7eatZunyPZbzyZzQeOkE85u4f0xjwQ9c+IFY77Mmwo3pRw2NAjinPInrcWNOfTI5LxYKgONJq9CHVV0jGvmZosj8b650HvHcVs7roH4uMyFFkVJwSKQs="

